# Interpreting Probabilities and "Expected" Values


-   A probability takes a value in the sliding scale from 0 to 100%.
-   Don’t just focus on computation; always remember to properly interpret probabilities.


::: {#exm-probability-interpret1}

In each of the following parts, which of the two probabilities, a or b, is larger, or are they equal?
You should answer conceptually without attempting any calculations.
Explain your reasoning.
:::

1.  Randomly select a man.

    a.  The probability that a randomly selected man who is greater than six feet tall plays in the NBA.
    a.  The probability that a randomly selected man who plays in the NBA is greater than six feet tall.


1. Randomly select a baby girl who was born in 1950.
    a.  The probability that a randomly selected baby girl born in 1950 is alive today.
    a.  The probability that a randomly selected baby girl born in 1950, who was alive at the end of 2020, is alive today. 
    \ 
    \ 
    \ 
    \ 
    \ 
    
-   A probability is a measure of the likelihood or degree of uncertainty or plausibility of an event.
-   A "conditional" probability revises this measure to reflect any additional information about the outcome of the underlying random phenomenon.
-   In a sense, all probabilities are conditional upon some information, even if that information is vague ("well, it has to be one of these possibilities").
Be careful to clearly identify what information is reflected in probabilities
-   When interpreting probabilities, consider the conditions under which the probabilities were computed, in the proper direction



::: {#exm-probability-interpret2}

In each of the following parts, which of the two probabilities, a or b, is larger, or are they equal?
You should answer conceptually without attempting any calculations.
Explain your reasoning.
:::

1. Flip a coin *which is known to be fair* 10 times.  

    a.  The probability that the results are, in order, HHHHHHHHHH.
    a.  The probability that the results are, in order, HHTHTTTHHT.

1. Flip a coin which is known to be fair 10 times.  

    a.  The probability that all 10 flips land on H.
    a.  The probability that exactly 5 flips land on H.
    

1.  In the [Powerball lottery](https://www.powerball.com/) there are roughly 300 million possible winning number combinations, all equally likely.

    a.  The probability you win the next Powerball lottery if you purchase a single ticket, 4-8-15-16-42, plus the Powerball number, 23
    a.  The probability you win the next Powerball lottery if you purchase a single ticket, 1-2-3-4-5, plus the Powerball number, 6.

1. Continuing with the Powerball

    a.  The probability that the numbers in the winning number are not in sequence (e.g., 4-8-15-16-42-23)
    a.  The probability that the numbers in the winning number are in sequence (e.g., 1-2-3-4-5-6)

1. Continuing with the Powerball

    a.  The probability that you win the next Powerball lottery if you purchase a single ticket.
    a.  The probability that someone wins the next Powerball lottery. (FYI: especially when the jackpot is large, there are hundreds of millions of tickets sold.) 
    \ 
    \ 
    \ 
    \ 
    \ 

-   When interpreting probabilities, be careful not to confuse "the particular" with "the general".
    -   **"The particular:"** A very specific event, surprising or not, often has low probability.
    -   **"The general:"** While a very specific event often has low probability, if there are many like   events their combined probability can be high.
-   Even if an event has extremely small probability, given enough
repetitions of the random phenomenon, the probability that the event occurs
on *at least one* of the repetitions is often high.
-   In general, even though the probability that something very specific happens to you today is often extremely small, the probability that something similar happens to someone some time is often quite high.
-   When assessing a numerical probability, always ask "probability of what"?  Does the probability represent "the particular" or "the general"? Is it the probability that the event happens in a single occurrence of the random phenomenon, or the probability that the event happens at least once in many occurrences?
-   Also distinguish between assumption and observation.
For example, if you assume that a coin is fair and the flips are independent, then all possible H/T sequences are equally likely.
However, if you observe the coin landing on heads on 20 flips in a row, then that might cast doubt on your assumption that the coin is fair.



::: {#exm-card-second-conditional}

Shuffle a standard deck of 52 playing cards (13 face values in each of 4 suits) and deal two cards without replacement.
:::


1.  What is the probability that the first card dealt is a heart? 
\
\
\
\
\
1.  What is the probability that the second card dealt is a heart? 
\
\
\
\
\
1.  What is the probability that the second card dealt is a heart if the first card dealt is a heart? 
\
\
\
\
\
1.  What is the probability that the second card dealt is a heart if the first card dealt is not a heart? 
\
\
\
\
\
1.  Revisit part 2.
What is the probability that the second card dealt is a heart?
Create a two-way table to answer this question. 
\
\
\
\
\

-   Be careful to distinguish between conditional and unconditional probabilities.
-   A conditional probability reflects additional information about the outcome of the random phenomenon.
-   In the absence of such information, we must continue to account for all the possibilities.
-   When computing probabilities, be sure to only reflect information that is known.
Especially when considering a phenomenon that happens in stages, don't assume that when considering what happens second that you know what happened first.


::: {#exm-base-rate-neglect}
Within both the colleges of Agriculture and Architecture at Cal Poly, about 49% of admitted students are female, about 84% of admitted students went to high school in CA, and the median GPA of admitted students is about 4.1.

An orientation group of 100 newly admitted Cal Poly students includes 75 students in Agriculture and 25 students in Architecture.
A student is randomly selected from this group.
The selected student is Maddie, who is female, went to high school in CA, and had a high school GPA of 4.1.
:::

Donny Don't says, "The information about Maddie applies equally well to Agriculture or Architecture and doesn't help us decide which college she's in, so it's just 50/50. Given the information about Maddie, the conditional probability that she is in Agriculture is 0.5."
Do you agree?
If not, what is the conditional probability that Maddie is in the college of Agriculture given the information about her? 
\
\
\
\
\


::: {#exm-ev-insurance}

This is a very simplified example illustrating the basic idea of how insurance works.
Every year an insurance company sells many thousands of car insurance policies to drivers within a particular risk class.
Each policyholder pays a "premium" of \$1000 at the start of the year, and the insurance company agrees to pay for the cost of all damages that occur during the year.
Suppose that each policy incurs damage  of either \$0, \$5000, \$20000, or \$50000 with the following probabilities.

| Amount of damage (\$) | Profit (\$) | Probability |
|----------------------:|------------:|------------:|
|                     0 |        1000 |       0.910 |
|                  5000 |       -4000 |       0.070 |
|                 20000 |      -19000 |       0.019 |
|                 50000 |      -49000 |       0.001 |

The insurance company's profit on a policy at the end of the year is the difference between the premium of \$1000 and any damage paid out.
For example, a policy that incurs no damage results in a profit of \$1000; a policy that incurs \$5000 in damage results in a profit of -\$4000 (that is, a loss of \$4000) for the insurance company. 
:::

1.  Interpret the probabilities 0.91, 0.07, 0.019, and 0.001 as long run relative frequencies in this context.
\
\
\
\
\
1.  Compute the probability that a policy results in a positive profit for the insurance company.
\
\
\
\
\
1.  Imagine 100,000 hypothetical policies.
How many of these policies would you expect to result in a profit of \$1000? -\$4000? -\$19000? -\$49000?
\
\
\
\
\
1.  What do you expect the total profit for these 100,000 policies to be?
\
\
\
\
\
1.  What do you expect the average profit per policy for these 100,000 policies to be?
\
\
\
\
\
1.  Compute the probability that a policy has a profit equal to the value from part 5.
\
\
\
\
\
1.  Compute the probability that a policy has a profit greater than the value from part 5.
\
\
\
\
\
1.  Is the value from part 5 the most likely value of profit for a single policy?
\
\
\
\
\
1.  Is the value from part 5 the profit you would expect for a single policy?
\
\
\
\
\
1.  Explain in what sense the value from part 5 is "expected".
\
\
\
\
\

-   The long run average value of a random quantity is called its "expected value".
-   Be careful: the term "expected value" is somewhat of a misnomer.
-   The expected value is *not* necessarily the value we expect on a single repetition of the random phenomenon, nor the most likely value (or even a possible value).
-   Rather, the expected is the value we expect to see on average in the long run over many repetitions.
-   A probability can be interpreted as a long run relative frequency; an expected value can be interpreted as a long run average value.





::: {#exm-ev-insurance-2}
Continuing @exm-ev-insurance.
We considered what we would expect for 100000 hypothetical policies, but what about an unspecified large number of policies?
:::

1.  Imagine that we have recorded the profit for each of a large number of policies (not necessarily 100000).
Explain in words the process by which you would compute the average profit per policy.
(In other, more general, words: how do you compute an average of a list of numbers?) 
\
\
\
\
\
1.  Given that the profit of any policy is either 1000, -4000, -19000, or -49000, how could we simplify the calculation of the sum in the previous part?
Write a general expression for the average profit per policy in this scenario. 
\
\
\
\
\
1.  What do you think the expression in the previous part converges to in the long run? 
\
\
\
\
\
1.  Explain how the value in the previous part is a "probability-weighted average value".
\
\
\
\
\
1.  Compute the expected value of damage (not profit) as a probability-weighted average value.
\
\
\
\
\

1.  Interpret the value from the previous part as a long run average value in this context.
\
\
\
\
\

1.  How is the expected value of profit related to the expected value of damage?
Does this make sense?
Why?
\
\
\
\
\

-   An expected value can be computed as a "probability-weighted average value"
-   But this is just a more compact way of computing an average in the usual way: add up all the values and divide by the number of values.
